[package]
name = "abgleich2"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
colored = "2.1.0"
config = "0.14.0"
console = "0.15.8"
indexmap = "2.5.0"
